#### Initialize interactive visualizations ####

https://plotly.com/python/getting-started/#overview|

In [1]:
%pip install plotly==5.18.0

Requirement already satisfied: plotly==5.18.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (5.18.0)
Requirement already satisfied: tenacity>=6.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from plotly==5.18.0) (9.0.0)
Requirement already satisfied: packaging in /Users/joshxi/Library/Python/3.12/lib/python/site-packages (from plotly==5.18.0) (24.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
# fig.write_html('first_figure.html', auto_open=True)

In [3]:
%pip install nbformat

Requirement already satisfied: nbformat in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbformat) (2.20.0)
Requirement already satisfied: jsonschema>=2.6 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from nbformat) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/joshxi/Library/Python/3.12/lib/python/site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in /Users/joshxi/Library/Python/3.12/lib/python/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (24.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (0.20.0)
Requirement already satisfied: platformdirs>=2.5 in /Users/joshxi/Library/Python/3.12/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.6)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import sqlalchemy
from sqlalchemy import Table, Column, String, MetaData

# สร้าง engine ที่ใช้ในการเชื่อมต่อกับ PostgreSQL server
# postgresql://[account]:[password]@localgos:[port]/[dbname]
engine1 = sqlalchemy.create_engine('postgresql://admin:root@localhost:5433/banking')

In [26]:
import pandas as pd
import numpy as np

df1 = pd.read_sql('SELECT * FROM account', engine1)
df2 = pd.read_sql('SELECT * FROM customer', engine1)
df3 = pd.read_sql('SELECT * FROM depositor', engine1)
df4 = pd.read_sql('SELECT * FROM loan', engine1)
df5 = pd.read_sql('SELECT * FROM borrower', engine1)
df6 = pd.read_sql('SELECT * FROM branch', engine1)

In [27]:
print(df1)
print(df2)
print(df3)
print(df4)
print(df5)
print(df6)

  account_number branch_name  balance
0              1           B    100.0
1              2           A     50.0
2              3           A     30.0
3              4           F    120.0
4              5           A    500.0
5              6           B    324.0
  customer_name customer_street customer_only
0          Alan     Mary_street             Y
1         Jason    Jason_street             N
2           Joe      Joe_street             Y
3         Keith    Keith_street             N
4          Mary     Mary_street             N
5          Mike     Mary_street             Y
  customer_name account_number
0           Joe              1
1           Joe              2
2           Joe              3
3         Keith              4
4         Keith              6
5          Mary              2
6          Mike              5
  loan_number branch_name  amount
0           1           B   100.0
1           2           E    27.0
2           3           F   543.0
3           4           A   129.0
4           5           A    26.0
5           6           B    67.0
  customer_name loan_number
0         Jason           2
1           Joe           1
2           Joe           3
3           Joe           6
4         Keith           4
5          Mary           5
  branch_name branch_city    assets
0           A   Riverside  100000.0
1           B          LA   20000.0
2           C  Long Beach   15000.0
3           D      Irvine   12000.0
4           E      Pomona    7000.0
5           F    San Jose   18000.0

In [23]:
df_output = pd.read_sql('SELECT customer_name, SUM(balance) as sum_balance FROM customer NATURAL JOIN depositor NATURAL JOIN account GROUP BY customer_name', engine1)
df_output

  customer_name  sum_balance
0           Joe        180.0
1          Mary         50.0
2          Mike        500.0
3         Keith        444.0

In [24]:
import plotly.express as px
fig = px.bar(df_output, x='customer_name', y='sum_balance')

import plotly.graph_objects as go
fig_widget = go.FigureWidget(fig)
fig_widget

FigureWidget({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': 'customer_name=%{x}<br>sum_balance=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'uid': 'b797cd1d-5fdb-412a-a7db-418b20c691f5',
              'x': array(['Joe', 'Mary', 'Mike', 'Keith'], dtype=object),
              'xaxis': 'x',
              'y': array([180.,  50., 500., 444.]),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'customer_name'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'sum_balance'}}}
})

In [30]:
ass_count = pd.read_sql("SELECT branch_name, assets FROM branch", engine1)
ass_count

  branch_name    assets
0           A  100000.0
1           B   20000.0
2           C   15000.0
3           D   12000.0
4           E    7000.0
5           F   18000.0

In [33]:
import plotly.express as px

fig = px.pie(ass_count, values='assets', names='branch_name', title='Branch assets')
fig.show()

In [35]:
acc_bal = pd.read_sql('select branch_name, account_number, balance from account natural join branch', con=engine1) # use engine1 from previous cell
# fig = px.bar(acc, x='founded', y='num_employees',
#              hover_data=['founded', 'num_employees'], color='industry',
#             height=400)
# fig.show()
acc_bal

  branch_name account_number  balance
0           B              1    100.0
1           A              2     50.0
2           A              3     30.0
3           F              4    120.0
4           A              5    500.0
5           B              6    324.0

In [47]:
fig_3 = px.bar(
    acc_bal, x='branch_name', y='balance', hover_data=['branch_name', 'balance'], 
    category_orders={'branch_name': sorted(acc_bal.branch_name.unique())},
    color='account_number', height=600,
    title='Account and balance in each branch'
)
fig_3.show()

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/plotly/express/_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [63]:
import pandas as pd
loan_bal = pd.read_sql('SELECT customer_name, SUM(amount) as total_loan FROM loan NATURAL JOIN customer NATURAL JOIN borrower GROUP BY customer_name', engine1)
acc_bal = pd.read_sql('SELECT customer_name, SUM(balance) as total_balance  FROM account NATURAL JOIN depositor GROUP BY customer_name', engine1)

  customer_name  total_balance
0          Mary           50.0
1          Mike          500.0
2         Keith          444.0
3           Joe          180.0

In [68]:
import plotly.express as px

merged = pd.merge(acc_bal, loan_bal, on='customer_name', suffixes=('_loan_bal', '_acc_bal'),how='outer')

merged.fillna(0, inplace=True)

melted = merged.melt(id_vars='customer_name', value_vars=['total_balance', 'total_loan'],
                           var_name='account_type', value_name='sum_values')


fig = px.bar(melted, x='customer_name', y='sum_values', color='account_type', barmode='group',
             title="Saving and loan balances of each customer")
fig.show()

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/plotly/express/_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.